import {OEmployee} from "./types"

export const listOf20MockedEmployees: OEmployee[] = [
	{
		firstName: "George",
		lastName: "Washington",
		startingDate: new Date("1789-04-30"),
		department: "Sales",
		dateOfBirth: new Date("1732-02-22"),
		street: "1600 Pennsylvania Avenue NW",
		city: "Washington",
		zipCode: "20500",
	},
	{
		firstName: "John",
		lastName: "Adams",
		startingDate: new Date("1797-03-04"),
		department: "Marketing",
		dateOfBirth: new Date("1735-10-30"),
		street: "1600 Pennsylvania Avenue NW",
		city: "Washington",
		zipCode: "20500",
	},
	{
		firstName: "Thomas",
		lastName: "Jefferson",
		startingDate: new Date("1801-03-04"),
		department: "Engineering",
		dateOfBirth: new Date("1743-04-13"),
		street: "1600 Pennsylvania Avenue NW",
		city: "Washington",
		zipCode: "20500",
	},
	{
		firstName: "James",
		lastName: "Madison",

		startingDate: new Date("1809-03-04"),
		department: "Human Resources",
		dateOfBirth: new Date("1751-03-16"),
		street: "1600 Pennsylvania Avenue NW",
		city: "Washington",
		zipCode: "20500",
	},
	{
		firstName: "James",
		lastName: "Monroe",
		startingDate: new Date("1817-03-04"),
		department: "Legal",
		dateOfBirth: new Date("1758-04-28"),
		street: "1600 Pennsylvania Avenue NW",
		city: "Washington",
		zipCode: "20500",
	},
	{
		firstName: "John",
		lastName: "Quincy",
		startingDate: new Date("1825-03-04"),
		department: "Sales",
		dateOfBirth: new Date("1767-07-11"),
		street: "1600 Pennsylvania Avenue NW",
		city: "Washington",
		zipCode: "20500",
	},
	{
		firstName: "Andrew",
		lastName: "Jackson",
		startingDate: new Date("1829-03-04"),
		department: "Marketing",
		dateOfBirth: new Date("1767-03-15"),
		street: "1600 Pennsylvania Avenue NW",
		city: "Washington",
		zipCode: "20500",
	},
	{
		firstName: "Martin",
		lastName: "Van Buren",
		startingDate: new Date("1837-03-04"),
		department: "Engineering",
		dateOfBirth: new Date("1782-12-05"),
		street: "1600 Pennsylvania Avenue NW",
		city: "Washington",
		zipCode: "20500",
	},
	{
		firstName: "William",
		lastName: "Henry Harrison",
		startingDate: new Date("1841-03-04"),
		department: "Human Resources",
		dateOfBirth: new Date("1773-02-09"),
		street: "1600 Pennsylvania Avenue NW",
		city: "Washington",
		zipCode: "20500",
	},
]